project_id = "fhtuqmdlgzmpsbflxhra"

[functions.contact-form]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.get-furgonetka-token]
verify_jwt = false

[functions.create-furgonetka-shipment]
verify_jwt = true

[functions.furgonetka-webhook]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false